CREATE LOGIN [emsuser1]
    WITH PASSWORD = N',uw|vh6{axai8kl{uarnxxs msFT7_&#$!~<tw:pP{|afdnc', SID = 0xFC59F17C9E5B6C4FA7BED0B58F3AC88B, DEFAULT_DATABASE = [EMS], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

